
# Data files
data.TraineeDataPath=TraineeData.json

data.TrainerDataPath=TrainerData.json

data.TrainingDataPath=TrainingData.json

# AOP properties
spring.aop.proxy-target-class=true

# Spring Boot actuator and health properties
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# logger properties
spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%5p) [%X{transactionId}] [%thread] %logger{36} : %msg%n


