spring:
  datasource:
    # database credentials
    url: 'jdbc:h2:mem:Gym_CRM_db;DB_CLOSE_DELAY=-1;MODE=MySQL;NON_KEYWORDS=USER'
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
    hikari:
      auto-commit: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    show-sql: true
    hibernate:
      # JPA properties
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: true
  jms:
    cache:
      # JMS Config
      enabled: false
    listener:
      session:
        acknowledge-mode: auto
      min-concurrency: 1
      max-concurrency: 1
    pub-sub-domain: false
logging:
  level:
    org:
      springframework:
        context:
          event:
            # logs
            EventListenerMethodProcessor: TRACE
