services:
  # main application
  main_app:
    build:
      context: ./GymCRMSystem
      dockerfile: Dockerfile
    container_name: gymcrmmainapp
    restart: unless-stopped
    depends_on:
      microservice_app:
        condition: service_started
      discovery_app:
        condition: service_started
      active_mq:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      - gym_crm_network

  # microservice up whose purpose is to maintain trainer's work information
  microservice_app:
    build:
      context: ./Trainer-history-service
      dockerfile: Dockerfile
    container_name: gymcrmmicroserviceapp
    restart: unless-stopped
    depends_on:
      discovery_app:
        condition: service_started
      active_mq:
        condition: service_started
    ports:
      - "8081:8081"
    networks:
      - gym_crm_network

  # special service that eradicates tight coupling between microservices
  discovery_app:
    build:
      context: ./GymCRMSystemDiscovery
      dockerfile: Dockerfile
    container_name: gymcrmdiscoveryapp
    restart: unless-stopped
    ports:
      - "8761:8761"
    networks:
      - gym_crm_network

  # messaging broker for async communication between microservices
  active_mq:
    image: apache/activemq-classic:latest
    container_name: activemqbroker
    ports:
      - "8161:8161"
      - "61616:61616"
    restart: unless-stopped
    networks:
    - gym_crm_network

  # nosql database used for storing trainer's work information(trainer history service uses it)
  mongo_db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart: unless-stopped
    networks:
      - gym_crm_network

networks:
  gym_crm_network:
    driver: bridge